### ISSUE TITLE
Playlist Support

### ISSUE THREAD

**Issue by Rodabaugh** [TheDemise/discord.js-musicbot-addon#3]
It would be great of this had support for queueing an entire Youtube playlist. I don't have a lot of experience with JS or the YouTube API, but I'll see about adding this myself if I can find the free time. Thanks for this addon though, it has helped me a lot!

**Comment by TheDemise** [comment]
That actually has been something I've been fiddling with a bit. I just haven't been able to do it with the previous modules I was using, but I might be able to cook something up now. I'm glad it could be of some help as well!

**Comment by TheDemise** [comment]
The new 1.5 update brings a beta version of the playlist feature, feel free to have a looksie at it.
But for now, this will remain closed.
