### ISSUE TITLE
Crashing when requesting music 

### ISSUE THREAD

**Issue by rethiable** [TheDemise/discord.js-musicbot-addon#9]
I've (hopefully) installed the bot correctly. After a bit of tinkering with the code to load the bot, I got it to load without crashing and join the discord server. When I typed in the music command and requested a song, the bot joined the channel and promptly crashed, here's the logs: 

(node:7480) ExperimentalWarning: The http2 module is an experimental API.
[Start] Mon Nov 06 2017 20:55:55 GMT-0500 (Eastern Standard Time)
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:254:10)
    at PassThrough.Writable.write (_stream_writable.js:288:21)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at emitThree (events.js:141:20)
    at DestroyableTransform.emit (events.js:217:7)
    at emitThree (events.js:136:13)
    at FfmpegCommand.emit (events.js:217:7)
    at emitEnd (C:\Users\Erin\Desktop\Bot ideas\MuffinBot™\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at C:\Users\Erin\Desktop\Bot ideas\MuffinBot™\node_modules\fluent-ffmpeg\lib\processor.js:433:16
    at C:\Users\Erin\Desktop\Bot ideas\MuffinBot™\node_modules\async\dist\async.js:421:16

(P.S. the TM is a joke and the bot is meant for a private server)

**Comment by TheDemise** [comment]
Firstly, any fluent-ffmpeg errors typically are a result of not having ffmpeg installed or installed improperly. Since the 1.4 (I may be wrong) update, the bot no longer uses the ffmpeg-binaries module and requires ffmpeg itself. The installation can vary between OS's.

Secondly, what version of the module and node are you using? And if the prior doesn't work, what did you change/tinker with in the code?

**Comment by rethiable** [comment]
I fixed it by uninstalling FFMPEG binaries and re-installing FFMPEG, thanks.

**Comment by rethiable** [comment]
But I do have another question. I have a command that allows the user to move the bot into another channel and play a pre-recorded MP3. I was testing this while the bot was playing music and the bot did move and play a part of the mp3, but then it left early and sent playback finished in chat. I want to know if I can detect when it's playing music, pause the music and then run the rest of the command.

**Comment by TheDemise** [comment]
This is something you'll probably have to figure out on your own, as it's not part of the module to do so. I myself wouldn't know how to do that, 'least not off the top of my head. Maybe once I'm in better health I could help you with that, but until now that'd be all you. Feel free to join the discord and message me or even ask the other few people there if they could even help if you still wish for it.
